version: '3.1'

services:
  implic-db:
    image: "ghcr.io/implic-sonar-ekip/implicaction-db:${PACKAGE_VERSION}"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'password'
      MYSQL_DATABASE: 'implicaction'
    ports:
      - "3306:3306"
    expose:
      - "3306"

  adminer:
    image: adminer
    restart: always
    ports:
      - "9030:8080"

  implic-app:
    depends_on: ["implic-db"]
    image: "ghcr.io/implic-sonar-ekip/implicaction-app:${PACKAGE_VERSION}"
    restart: always
    environment:
      DB_URI: mysql://implic-db:3306/implicaction
      DB_USER: root
      DB_PASS: password
      SMTP_HOST: smtp.mailtrap.io
      SMTP_PORT: 2525
      SMTP_USER: 5c354372a1d5da
      SMTP_PASS: 6b3338fa1cc8b9
      KS_PATH: /implicaction.jks
      KS_NAME: implicaction
      KS_PASSWORD: .fxG3KPB.
      APP_URL: http://localhost:8080
      CONTACT_EMAIL: contact@implicaction.eu
      AWS_ACCESS_KEY: ""
      AWS_SECRET_KEY: ""
      AWS_REGION: ""
    ports:
      - "8080:8080"
    expose:
      - "8080"
