name: My Workflow

on:
  push:
    branches:
    - workflow
  pull_request:
    branches:
    - main

jobs:
  front:
    defaults:
      run:
        shell: bash
        working-directory: frontend-implicaction
    name: Front workflow
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: use nodejs action
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'
      - name: Install dependencies
        run: npm install
      # - name: Running unit tests
      #   run: npm test
      - name: Build
        run: npm build

  back:
    name: Backend workflow
    runs-on: ubuntu-latest
    steps:
      - name: Todo
        run: echo Todo
